### ISSUE TITLE
RuntimeError: convolution10_bias is not presented

### ISSUE THREAD

**Issue by burness** [xlvector/mx-fast-neural-style#1]
Hi @xlvector:

When I run your model use the command `python boost_inference.py ./model/2/v3_0002-0026000.params googlenet-tflearn-accuracy-loss.png` here, i get an error :

```
2016-12-23 23:25:56,339 block: c9s1-32
2016-12-23 23:25:56,340 block: d64
2016-12-23 23:25:56,340 block: d128
2016-12-23 23:25:56,340 block: R128
2016-12-23 23:25:56,341 block: R128
2016-12-23 23:25:56,341 block: R128
2016-12-23 23:25:56,341 block: R128
2016-12-23 23:25:56,342 block: R128
2016-12-23 23:25:56,342 block: u64
2016-12-23 23:25:56,342 block: u32
2016-12-23 23:25:56,342 block: c9s1-3
2016-12-23 23:25:56,343 sym ok
2016-12-23 23:25:56,343 define module ok
2016-12-23 23:25:56,354 module bind ok
Traceback (most recent call last):
  File "boost_inference.py", line 23, in <module>
    gen.load_params(sys.argv[1])
  File "/Users/burness/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 537, in load_params
    self.set_params(arg_params, aux_params)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 503, in set_params
    allow_missing=allow_missing, force_init=force_init)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 198, in init_params
    _impl(name, arr, arg_params)
  File "/Users/burness/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 191, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: convolution10_bias is not presented
```

**Comment by burness** [comment]
@xlvector  Never mind, I read your code and found that i use this code in a wrong way 😆
